FROM openjdk:11-jre-slim

COPY login-1.0-jar-with-dependencies.jar /home/ubuntu/dockerfile/JAVA/jar-para-vm/login-1.0-jar-with-dependencies.jar

CMD ["java","-jar","/home/ubuntu/dockerfile/JAVA/jar-para-vm/login-1.0-jar-with-dependencies.jar"]